// ── Product page ──────────────────────────────────────────────────────────────

export const page            = 'min-h-screen bg-white';
export const loadingPage     = 'min-h-screen flex items-center justify-center';
export const loadingSpinner  = 'w-10 h-10 border-4 border-pink-400 border-t-transparent rounded-full animate-spin';
export const notFoundPage    = 'min-h-screen flex flex-col items-center justify-center gap-6';
export const notFoundText    = 'text-2xl font-display font-bold text-dark';
export const notFoundLink    = 'px-6 py-3 bg-dark text-white rounded-full font-semibold hover:bg-opacity-90 transition-all cursor-pointer whitespace-nowrap';
export const nav             = (scrolled: boolean) => `fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${scrolled ? 'bg-white shadow-md' : 'bg-white/95 backdrop-blur-sm shadow-sm'}`;
export const navContainer    = 'max-w-7xl mx-auto px-4 sm:px-6 py-3 sm:py-4 flex items-center justify-between';
export const logoWrapper     = 'flex items-center space-x-2 cursor-pointer';
export const logoIcon        = 'w-10 h-10 bg-pink-400 rounded-full flex items-center justify-center';
export const logoText        = 'font-display font-bold text-xl text-dark';
export const navRight        = 'flex items-center gap-4 text-dark';
export const navLink         = 'hidden md:block hover:text-pink-500 transition-colors text-sm font-medium cursor-pointer';
export const cartBtn         = 'flex items-center gap-2 px-5 py-2 bg-dark text-white rounded-full text-sm font-semibold hover:bg-opacity-90 transition-all whitespace-nowrap cursor-pointer';
export const breadcrumbBar   = 'pt-20 sm:pt-24 pb-4 max-w-7xl mx-auto px-4 sm:px-6';
export const breadcrumbInner = 'flex items-center gap-2 text-sm text-gray-400';
export const breadcrumbLink  = 'hover:text-dark transition-colors cursor-pointer';
export const mainContent     = 'max-w-7xl mx-auto px-4 sm:px-6 py-6 sm:py-8';
export const productGrid     = 'grid grid-cols-1 lg:grid-cols-2 gap-8 lg:gap-16';
export const infoCol         = 'flex flex-col gap-6';
const categoryColors: Record<string, string> = {
  girl: 'bg-pink-100 text-pink-600',
  boy: 'bg-sky-100 text-sky-600',
  adult: 'bg-stone-100 text-stone-600',
  medical: 'bg-red-50 text-red-600',
};
export const categoryBadge   = (category: string) => `text-xs font-bold uppercase tracking-wider px-3 py-1 rounded-full ${categoryColors[category] ?? 'bg-yellow-100 text-yellow-700'}`;
export const promoBadge      = 'text-xs font-bold uppercase tracking-wider px-3 py-1 rounded-full bg-red-100 text-red-500';
export const heading         = 'font-display font-black text-2xl sm:text-3xl md:text-4xl text-dark leading-tight mb-2';
export const starsRow        = 'flex items-center gap-1';
export const ratingsText     = 'text-sm text-gray-400';
export const priceRow        = 'flex items-baseline gap-3';
export const price           = 'text-2xl sm:text-3xl md:text-4xl font-black text-dark';
export const oldPrice        = 'text-xl text-gray-400 line-through';
export const description     = 'text-gray-500 text-sm leading-relaxed';
export const featuresGrid    = 'grid grid-cols-1 sm:grid-cols-2 gap-3';
export const featureRow      = 'flex items-center gap-2 text-sm text-dark';
export const featureIconBox  = 'w-5 h-5 flex items-center justify-center';
export const colorLabel      = 'text-sm font-semibold text-dark mb-3';
export const colorsRow       = 'flex items-center gap-2 sm:gap-3 flex-wrap';
export const colorBtn        = (selected: boolean, colorClass: string) => `w-10 h-10 rounded-full ${colorClass} transition-all cursor-pointer border-2 ${selected ? 'border-dark ring-2 ring-dark ring-offset-2 scale-110' : 'border-transparent hover:scale-105'}`;
export const sizeRow         = 'flex items-center gap-3';
export const sizeBtn         = (selected: boolean) => `w-12 h-12 rounded-xl text-sm font-bold transition-all cursor-pointer whitespace-nowrap ${selected ? 'bg-dark text-white shadow-md' : 'bg-gray-100 text-dark hover:bg-gray-200'}`;
export const sizeHint        = 'text-xs text-gray-400 mt-2';
export const wristGuideCard  = 'rounded-2xl border border-pink-100 bg-pink-50/60 p-4';
export const wristGuideHeader = 'flex items-center gap-2 mb-3';
export const wristGuideTitle = 'text-sm font-bold text-dark';
export const wristGuideTableWrap = 'overflow-x-auto rounded-xl border border-pink-100 bg-white';
export const wristGuideTable = 'w-full sm:min-w-[440px] border-collapse text-xs';
export const wristGuideHeadCell = 'px-3 py-2 text-left font-semibold text-gray-500 uppercase tracking-wide border-b border-pink-100';
export const wristGuideRow = 'odd:bg-white even:bg-pink-50/50';
export const wristGuideCellStrong = 'px-3 py-2 font-bold text-dark border-b border-pink-100';
export const wristGuideCell = 'px-3 py-2 text-gray-600 border-b border-pink-100';
export const wristGuideHint = 'text-xs text-gray-500 mt-3 leading-relaxed';
export const addToCartRow    = 'flex flex-col sm:flex-row items-stretch sm:items-center gap-3 sm:gap-4';
export const qtyWrapper      = 'flex items-center border border-gray-200 rounded-xl overflow-hidden';
export const qtyBtn          = 'w-12 h-12 flex items-center justify-center text-dark hover:bg-gray-100 transition-all cursor-pointer text-xl';
export const qtyValue        = 'w-12 text-center font-bold text-dark text-sm';
export const addBtn          = (added: boolean) => `flex-1 py-4 rounded-xl font-bold text-sm transition-all cursor-pointer whitespace-nowrap flex items-center justify-center gap-2 ${added ? 'bg-green-500 text-white' : 'bg-dark text-white hover:bg-opacity-90 hover:shadow-lg'}`;
export const stockRow        = 'flex items-center gap-2 text-sm';
export const stockDot        = (inStock: boolean) => `w-2 h-2 rounded-full ${inStock ? 'bg-green-500' : 'bg-orange-400'}`;
export const stockText       = (inStock: boolean) => inStock ? 'text-green-600' : 'text-orange-500';
export const deliveryRow     = 'flex flex-col sm:flex-row items-start sm:items-center gap-3 sm:gap-6 py-4 border-t border-gray-100';
export const deliveryItem    = 'flex items-center gap-2 text-sm text-gray-500';
export const deliveryIconBox = 'w-5 h-5 flex items-center justify-center';
export const qrSection       = 'mt-12 sm:mt-20';
export const qrHeader        = 'text-center mb-10';
export const qrEyebrow       = 'text-gray-400 text-sm font-medium tracking-wider uppercase mb-3';
export const qrTitle         = 'font-display font-black text-2xl sm:text-3xl md:text-4xl text-dark';
export const qrSubtitle      = 'text-gray-500 mt-3 max-w-xl mx-auto text-sm';
export const qrWrapper       = 'max-w-2xl mx-auto';
export const relatedSection  = 'mt-16 sm:mt-24';
export const relatedTitle    = 'font-display font-black text-2xl sm:text-3xl text-dark mb-6 sm:mb-10';
export const relatedGrid     = 'grid grid-cols-1 md:grid-cols-2 gap-8';
export const relatedLink     = 'group cursor-pointer block';
export const relatedImgBox   = (category: string) => `${category === 'girl' ? 'bg-pink-100' : category === 'boy' ? 'bg-sky-100' : 'bg-yellow-100'} rounded-3xl p-4 sm:p-8 mb-4 overflow-hidden relative h-48 sm:h-64 flex items-center justify-center transition-transform duration-300 group-hover:scale-105`;
export const relatedImg      = 'w-full h-full object-contain drop-shadow-xl';
export const relatedInfoRow  = 'flex items-center justify-between';
export const relatedName     = 'font-display font-semibold text-lg text-dark';
export const relatedPrice    = 'text-xl font-bold text-dark';
export const relatedBtn      = 'text-sm font-semibold text-dark border-2 border-dark px-4 py-2 rounded-full group-hover:bg-dark group-hover:text-white transition-all whitespace-nowrap';
export const footerEl        = 'mt-24 bg-stone-100 py-10';
export const footerInner     = 'max-w-7xl mx-auto px-6 flex flex-col md:flex-row items-center justify-between gap-4';
export const footerLogo      = 'flex items-center gap-2 cursor-pointer';
export const footerLogoIcon  = 'w-8 h-8 bg-pink-400 rounded-full flex items-center justify-center';
export const footerLogoText  = 'font-display font-bold text-dark';
export const footerCopyright = 'text-gray-400 text-sm';
export const footerLinks     = 'flex items-center gap-4 text-sm text-gray-400';
export const footerLink      = 'hover:text-dark transition-colors cursor-pointer';
